### ISSUE TITLE
怎么使用弹弹play播放器

### ISSUE THREAD

**Issue by terwer** [cxfksword/jellyfin-plugin-danmu#1]
感谢作者的插件，目前生成了插件xml文件，但是jellyfin默认的播放器没有弹幕。怎么把 [弹弹play](https://www.dandanplay.com/) 集成到jellyfin 呢，没找到方法。

**Comment by cxfksword** [comment]
弹弹play只能通过smb共享的方式，本地播放，再手工选择加载xml弹幕

**Comment by terwer** [comment]
感谢，共享方式也能接受。目前已经用上了太好了。
