### ISSUE TITLE
[需求]Emby支持

### ISSUE THREAD

**Issue by ArthurSmoke** [cxfksword/jellyfin-plugin-danmu#11]
是否能提供emby支持？

**Comment by cxfksword** [comment]
没用过emby，等有时间再去研究下，欢迎PR😃

**Comment by jy02919061** [comment]
同求 大佬辛苦

**Comment by tan0105** [comment]
+1，大佬赶紧用用emby，比jellyfin好看

**Comment by shuer001** [comment]
+1 还是emby用户多，jellyfin 客户端不太方便

**Comment by blacktea1891** [comment]
虽然emby和jellyfin都在用，但是希望增加emby支持，emby只有dandan的，爱优腾的没有支持

**Comment by cxfksword** [comment]
@fengymi 已经实现 emby 版：https://github.com/fengymi/emby-plugin-danmu

**Comment by jshir8** [comment]
> [@fengymi](https://github.com/fengymi) 已经实现 emby 版：https://github.com/fengymi/emby-plugin-danmu

@fengymi 大佬那边说不计划再用了，没有支持Bilibili，大佬有没有可能后续支持一下Emby呀~

**Comment by Summer-Tail** [comment]
> [@fengymi](https://github.com/fengymi) 已经实现 emby 版：https://github.com/fengymi/emby-plugin-danmu

该项目作者已经弃坑，希望重新提起支持Emby的计划
