### ISSUE TITLE
所有集数用的都是第一集的弾幕

### ISSUE THREAD

**Issue by hstonc** [cxfksword/jellyfin-plugin-danmu#15]
目前只在勇者义彦这部剧集发现这个问题，有使用修改字幕的功能重新下载过，弾幕来源是bilibili(只有这个源)
https://www.aliyundrive.com/s/CeRDB9XeGaK
每一集和每一季都有被正常识别到，命名也是单纯的以S和Ep这样的规则来的
原本以为是剧需要会员导致的，又试了同样需要会员，弾幕来源也是bilibili的蜡笔小新但是也是正常的

**Comment by cxfksword** [comment]
你点剧集的b站元数据链接能不能进到对应那集的页面？
