### ISSUE TITLE
请问如果片源就是外挂字幕的话，是不是只能弹幕字幕二选一，jellyfin貌似不支持双字幕，或者有没有啥插件可以实现

### ISSUE THREAD

**Issue by Bu-Hong** [cxfksword/jellyfin-plugin-danmu#16]
如题

**Comment by cxfksword** [comment]
最好是用支持xml格式的播放器播放，如弹弹play，假如是ass格式，需要用合并工具和原电影字幕合并为一个字幕

**Comment by Jumeng-ms** [comment]
> 最好是用支持xml格式的播放器播放，如弹弹play，假如是ass格式，需要用合并工具和原电影字幕合并为一个字幕

弹弹 无法直接播放jellyfin 的片源 挺麻烦的

**Comment by cxfksword** [comment]
> > 最好是用支持xml格式的播放器播放，如弹弹play，假如是ass格式，需要用合并工具和原电影字幕合并为一个字幕
> 
> 弹弹 无法直接播放jellyfin 的片源 挺麻烦的

弹弹是支持浏览器唤醒的，正常jellyfin加个js扩展就可以，不过现在协议只支持视频播放，不支持弹幕

**Comment by Byelliot** [comment]
写了个字幕合并的py脚本，srt字幕提取 srt转ass ass合并
https://github.com/Byelliot/Subtitlefusion
