### ISSUE TITLE
[需求]请求支持jellyfin 10.9.0

### ISSUE THREAD

**Issue by xyz0101** [cxfksword/jellyfin-plugin-danmu#18]
我的是10.9.0的版本，发现并没有设置字幕的选项
![image](https://user-images.githubusercontent.com/20569072/231432329-aca60a7c-9820-4325-a04d-f1ea94c8507a.png)

![image](https://user-images.githubusercontent.com/20569072/231432185-49370a14-27b7-4153-aa16-8436b004df77.png)

**Comment by verydemo** [comment]
![image](https://github.com/cxfksword/jellyfin-plugin-danmu/assets/29354679/654fe7ef-e65f-4b60-951f-67b7f847bbdd)
![image](https://github.com/cxfksword/jellyfin-plugin-danmu/assets/29354679/83f8ad39-fb56-44c4-a221-31429dd5f944)
10.8.11 也没有字体选项， 10.8.x 具体是支持哪个版本呢

**Comment by Izumiko** [comment]
10.9正式版已出
