### ISSUE TITLE
能添加自动合并原字幕的选项吗

### ISSUE THREAD

**Issue by eventhorizonsky** [cxfksword/jellyfin-plugin-danmu#21]
目前jellyfin只允许同时加载一个ASS，能否在保存ASS时检测本地是否已经存在字幕文件，如存在则合并弹幕和字幕为一个ASS

**Comment by cxfksword** [comment]
你这字幕文件是外置的吗？现在高清源都喜欢用PGS图片字幕，无法合并

**Comment by Byelliot** [comment]
写了个字幕合并的py脚本，srt字幕提取 srt转ass ass合并
https://github.com/Byelliot/Subtitlefusion
