### ISSUE TITLE
使用了插件之后在本地文件夹下生成了ass和xml弹幕文件，但是jellyfin上没有加载选项，只能用本地的potplayer看么

### ISSUE THREAD

**Issue by shibuxing** [cxfksword/jellyfin-plugin-danmu#25]

**Comment by cxfksword** [comment]
你jellyfin使用什么客户端，ass就是普通字幕，播放器中切换下字幕就行

**Comment by squalychen** [comment]
切换ass字幕，就没有中文字幕了，怎么看啊，汗，我也是emby用，目前只能用jellyfin生成ass字幕给tv端用，这项目很好，希望会更加成熟。

**Comment by TomoeMami** [comment]
> 切换ass字幕，就没有中文字幕了，怎么看啊，汗，我也是emby用，目前只能用jellyfin生成ass字幕给tv端用，这项目很好，希望会更加成熟。

emby还有其他的项目：https://danmaku.movie.kg/

**Comment by missing233** [comment]
> > 切换ass字幕，就没有中文字幕了，怎么看啊，汗，我也是emby用，目前只能用jellyfin生成ass字幕给tv端用，这项目很好，希望会更加成熟。
> 
> emby还有其他的项目：https://danmaku.movie.kg/

这个不开源而且好久没更新了，目前iOS客户端已经不能正常使用
