### ISSUE TITLE
如何指定av/bv号

### ISSUE THREAD

**Issue by lzyl42** [cxfksword/jellyfin-plugin-danmu#27]
> B站电影或季元数据也支持手动指定BV/AV号

请问如何指定？元数据填上会自动跳转到对应的季/集的前缀

**Comment by cxfksword** [comment]
是元数据填bv号就可以了，前缀是什么意思

**Comment by lzyl42** [comment]
> 是元数据填bv号就可以了，前缀是什么意思

哦，我试了下，虽然jellyfin里的跳转链接不正常但是弹幕下载是正常的。那没问题了。
还有个请求，能否每集和视频指定分p号对应上，这样b站有些多季合集的视频可以手动匹配下

**Comment by cxfksword** [comment]
> > 是元数据填bv号就可以了，前缀是什么意思
> 
> 哦，我试了下，虽然jellyfin里的跳转链接不正常但是弹幕下载是正常的。那没问题了。 还有个请求，能否每集和视频指定分p号对应上，这样b站有些多季合集的视频可以手动匹配下

举个例子我看一下
