### ISSUE TITLE
安装插件后通过网络监控发现随时都在从api.bilibili.com和api.dandanplay.net下载东西，请问正常吗

### ISSUE THREAD

**Issue by Kongsama171** [cxfksword/jellyfin-plugin-danmu#28]
![屏幕截图 2024-01-14 093125](https://github.com/cxfksword/jellyfin-plugin-danmu/assets/86615415/125ed02d-2f4a-4e43-acc3-4b2026ca22b5)

**Comment by cxfksword** [comment]
可以看下日志在处理什么

**Comment by Kongsama171** [comment]
重启插件后问题解决。看日志是一直在扫描弹幕
