### ISSUE TITLE
jellyfin如何设置多集的剧场版动画来匹配弹幕

### ISSUE THREAD

**Issue by Kongsama171** [cxfksword/jellyfin-plugin-danmu#29]
比如伤物语三部电影在弹弹play里面显示为三集，也需要放在伤物语Season 1下面，按照S01Exx的形式来命名吗？
![屏幕截图 2024-01-15 114326](https://github.com/cxfksword/jellyfin-plugin-danmu/assets/86615415/c16db9ed-8fb1-4e9a-93c2-ea4db520b02a)

**Comment by cxfksword** [comment]
电影都是每部分开刮削的，这种情况只能每部自己修改元数据匹配下，直接填对应的episodeId

**Comment by Kongsama171** [comment]
好的谢谢
