### ISSUE TITLE
Jellyfin 客户端自荐

### ISSUE THREAD

**Issue by dragonflylee** [cxfksword/jellyfin-plugin-danmu#34]
最近的发布的 [Switchfin](https://github.com/dragonflylee/switchfin/releases/tag/0.5.0) 已经集成了本插件的API支持，可以直接连接Jellyfin服务器加载弹幕

![image](https://github.com/cxfksword/jellyfin-plugin-danmu/assets/6219280/991e2e24-673d-4fbf-9ff7-8b99ce83183d)

支持 Windows/MacOS/Linux 桌面平台

**Comment by cxfksword** [comment]
👍我加下到README中
