### ISSUE TITLE
能否增加港澳台的弹幕支持？以及生成ass字幕时合并原有字幕？

### ISSUE THREAD

**Issue by Izumiko** [cxfksword/jellyfin-plugin-danmu#4]
- 在设置中能否增加BiliRoaming的[公共解析服务器](https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8)支持，下载一下港澳台的弹幕
- 现在播放外挂字幕的视频时，字幕和ass弹幕不能同时在网页端加载，能否增加一个选项，在生成ass格式弹幕时，把字幕也合并进去？

**Comment by cxfksword** [comment]
解析服务器只是用来获取播放地址，插件还需要获取港澳的番剧信息，获取不到

合并ass的话，多字幕时没法知道实际要合并哪一个，用其他工具有界面操作的更合适些

**Comment by Izumiko** [comment]
那看来得通过香港的代理服务器来获取了😥

**Comment by cxfksword** [comment]
> 那看来得通过香港的代理服务器来获取了😥

是，或者等后面使用弹弹play的弹幕

**Comment by goodmangll** [comment]
> 解析服务器只是用来获取播放地址，插件还需要获取港澳的番剧信息，获取不到
> 
> 合并ass的话，多字幕时没法知道实际要合并哪一个，用其他工具有界面操作的更合适些

能否都合并，比如我有2个字幕叫 “大闹天宫.chi.简体中字.ass“ “大闹天宫.chi.简英双字.ass” 合并为 “大闹天宫.chi.简体中字_弹幕.ass“ “大闹天宫.chi.简英双字_弹幕.ass”

**Comment by goodmangll** [comment]
> 解析服务器只是用来获取播放地址，插件还需要获取港澳的番剧信息，获取不到
> 
> 合并ass的话，多字幕时没法知道实际要合并哪一个，用其他工具有界面操作的更合适些

能否都合并，比如我有2个字幕叫 “大闹天宫.chi.简体中字.ass“ “大闹天宫.chi.简英双字.ass” 合并为 “大闹天宫.chi.简体中字_弹幕.ass“ “大闹天宫.chi.简英双字_弹幕.ass”
