### ISSUE TITLE
我发现使用这个插件的字幕就无法开启次字幕诶

### ISSUE THREAD

**Issue by louenjoy** [cxfksword/jellyfin-plugin-danmu#46]
看番的时候只能翻译字幕和弹幕字幕二选一.请问有没有办法同时打开两个字母

**Comment by cxfksword** [comment]
你用什么播放器放? 可以换支持xml格式的播放器

**Comment by Cxquang** [comment]
@cxfksword 我使用fileball登录emby,电影目录已经有xml的弹幕文件了，但播放为啥还是没有弹幕，是需要开高级功能吗
