### ISSUE TITLE
希望能jellyfin原生支持这个弹幕插件，换播放器的话用jellyfin就没有意义了

### ISSUE THREAD

**Issue by nathandingx** [cxfksword/jellyfin-plugin-danmu#51]
我使用这个插件后，发现jellyfin播放器居然无法显示弹幕，感觉它存在的意义被抹杀了

**Comment by fengymi** [comment]
> 我使用这个插件后，发现jellyfin播放器居然无法显示弹幕，感觉它存在的意义被抹杀了

TV端可以使用这个
https://github.com/fengymi/jellyfin-androidtv/releases/tag/v0.0.0-beta
