### ISSUE TITLE
能否支持合并到已有的的字幕里？

### ISSUE THREAD

**Issue by ayellowcat** [cxfksword/jellyfin-plugin-danmu#54]
因为jellyfin的移动和电视客户端几乎都只支持外挂一个字幕，所以希望可以增加，弹幕与已有的srt或ass合并成一个新的字幕文件，这样字幕和弹幕就同时具备了

**Comment by cxfksword** [comment]
可以试下这工具: https://github.com/cxfksword/jellyfin-plugin-danmu/issues/21#issuecomment-1734553492
