### ISSUE TITLE
n1盒子刷机kodi系统，加载ass弹幕文件，经常显示不正常，显示为中文乱码

### ISSUE THREAD

**Issue by x2rr** [cxfksword/jellyfin-plugin-danmu#55]
看电视剧，有些集弹幕显示正常，有些显示不正常（中文乱码）
查了一下好像是文件编码问题
请问插件保存文件时，是否保存为utf-8编码？

**Comment by cxfksword** [comment]
现在就是utf8的，你可以用文本编辑器看下

**Comment by VickyRain** [comment]
> 现在就是utf8的，你可以用文本编辑器看下
抱歉，我提了个[新issue](https://github.com/cxfksword/jellyfin-plugin-danmu/issues/57)，目前感觉可能和emoji有关，删除emoji或者编码改为带BOM的UTF-8或Unicode都不会乱码
