### ISSUE TITLE
内存占用问题

### ISSUE THREAD

**Issue by xxzj990** [cxfksword/jellyfin-plugin-danmu#56]
没有人发现内存占用异常的问题吗？如下图：

![微信截图_20241014095854](https://github.com/user-attachments/assets/ff56b2f8-5cf1-45dd-9a16-0437db95a970)

这个是跑了3天的效果，如果时间再长点，比如2-3周，能占用到5-6G。应该还会继续涨，直到内存爆满。

我的环境是docker,用的镜像是：linuxserver/jellyfin:10.9.8。

如果卸载弹幕插件就没有内存异常的问题。

**Comment by cxfksword** [comment]
jellyfin是一直有影片入库在不断下载弹幕? 还是不下载内存占用也不断增长?

**Comment by xxzj990** [comment]
> jellyfin是一直有影片入库在不断下载弹幕? 还是不下载内存占用也不断增长?


一直有影片入库，我订阅了RSS自动下载。@cxfksword

**Comment by xxzj990** [comment]
下图是今天早上的状态：

![微信截图_20241015085047](https://github.com/user-attachments/assets/a3ae630e-eb02-4458-aed1-5210a0600768)

**Comment by xxzj990** [comment]
和库的大小有没有关系，我的电影有1万七左右，电视有2500左右。我可以再观察一段时间看看，反正我记得上次重启jellyfin的时候占用了6个多G的内存。

**Comment by xxzj990** [comment]
后期好像就不继续涨了，这个问题暂时影响不是很大，可以通过定时重启解决问题，先关闭了。

![微信截图_20241031110613](https://github.com/user-attachments/assets/ac57db3f-bc66-4382-8c0d-64935df7672a)
