### ISSUE TITLE
jellyfin服务器端更新最新版本后，fengymi-jellyfinTV版无法正常烧录字幕

### ISSUE THREAD

**Issue by nathandingx** [cxfksword/jellyfin-plugin-danmu#64]
jellyfin服务器端版本: ghcr.io/linuxserver/jellyfin:nightly-version-2024110405ubu2404
fengymi-jellyfinTV版本:最新版本

错误:fengymi-jellyfinTV播放视频时一直重复提示“烧录字幕中，这可能需要几秒钟…”，卡住无法播放，

fengymi-jellyfinTV点开视频时不启用字幕，视频、弹幕能正常播放；
使用官方jellyfin能正常播放字幕、视频，但无法播放弹幕

总体判断应该是fengymi-jellyfinTV不兼容最新版本的jellyfin服务器端，求大佬更新，拜托了🙏🏻🙏🏻

**Comment by cxfksword** [comment]
这个是大佬 @fengymi 修改的，你要找他改下
